export const plants = [
  {
    id: 1,
    plantName: "Pascal",
    category: "Natural Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-1.jpg",
    price: 499,
    rating: 3.5,
    sales: 12,
  },
  {
    id: 2,
    plantName: "White Flower",
    category: "Natural Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-2.jpg",
    price: 399,
    rating: 4,
    sales: 18,
  },
  {
    id: 3,
    plantName: "Cactus",
    category: "Artificial Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-3.jpg",
    price: 599,
    rating: 4.5,
    sales: 92,
  },
  {
    id: 4,
    plantName: "Aloevera",
    category: "Natural Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-4.jpg",
    price: 999,
    rating: 2.5,
    sales: 78,
  },
  {
    id: 5,
    plantName: "Pink Ful",
    category: "Floral Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-5.jpg",
    price: 299,
    rating: 4.5,
    sales: 92,
  },
  {
    id: 6,
    plantName: "Little Herb",
    category: "Herb Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-6.jpg",
    price: 299,
    rating: 4.5,
    sales: 79,
  },
  {
    id: 7,
    plantName: "Long Grass",
    category: "Natural Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-7.jpg",
    price: 299,
    rating: 2.5,
    sales: 44,
  },
  {
    id: 8,
    plantName: "Tiny Herb",
    category: "Herb Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-8.jpg",
    price: 399,
    rating: 4,
    sales: 9,
  },
  {
    id: 9,
    plantName: "Hot Chilli Plant",
    category: "Herb Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-9.jpg",
    price: 799,
    rating: 3.5,
    sales: 48,
  },
  {
    id: 10,
    plantName: "Rubber Herb",
    category: "Artificial Plants",
    desc: "Most beautiful room decor.",
    img: "/img/plant-10.jpg",
    price: 899,
    rating: 2.5,
    sales: 27,
  },
  {
    id: 11,
    plantName: "Little Herb",
    category: "Floral Plants",
    desc: "Beauty remedy for your room.",
    img: "/img/plant-11.jpg",
    price: 1999,
    rating: 4.5,
    sales: 60,
  },
  {
    id: 12,
    plantName: "Leafy Long",
    category: "Herb Plants",
    desc: "Synchronise with your serenity.",
    img: "/img/plant-12.jpg",
    price: 499,
    rating: 2.5,
    sales: 41,
  },
  {
    id: 13,
    plantName: "Peace Perl",
    category: "Floral Plants",
    desc: "Beauty remedy for your room.",
    img: "/img/plant-13.jpg",
    price: 699,
    rating: 2,
    sales: 33,
  },
  {
    id: 14,
    plantName: "Rubber Herb",
    category: "Artificial Plants",
    desc: "Most beautiful room decor.",
    img: "/img/plant-10.jpg",
    price: 399,
    rating: 3.5,
    sales: 80,
  },
  {
    id: 15,
    plantName: "Little Herb",
    category: "Herb Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-6.jpg",
    price: 99,
    rating: 4.5,
    sales: 79,
  },
  {
    id: 16,
    plantName: "White Flower",
    category: "Natural Plants",
    desc: "Perfect for your home garden.",
    img: "/img/plant-2.jpg",
    price: 899,
    rating: 3.5,
    sales: 40,
  },
];

export const reviews = [
  {
    id: 1,
    name: "John Doe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque fugiat modi a, quasi enim libero suscipit ipsam omnis placeat quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, dignissimos.",
    img: "/img/reviewer-1.jpg",
    profession: "Youtuber",
    rating: 5,
  },
  {
    id: 2,
    name: "John Doe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque fugiat modi a, quasi enim libero suscipit ipsam omnis placeat quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, dignissimos.",
    img: "/img/reviewer-2.jpeg",
    profession: "Youtuber",
    rating: 4.5,
  },
  {
    id: 3,
    name: "John Doe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque fugiat modi a, quasi enim libero suscipit ipsam omnis placeat quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, dignissimos.",
    img: "/img/reviewer-2.jpeg",
    profession: "Youtuber",
    rating: 4,
  },
  {
    id: 4,
    name: "John Doe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque fugiat modi a, quasi enim libero suscipit ipsam omnis placeat quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, dignissimos.",
    img: "/img/reviewer-1.jpg",
    profession: "Youtuber",
    rating: 4.5,
  },
  {
    id: 5,
    name: "John Doe",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque fugiat modi a, quasi enim libero suscipit ipsam omnis placeat quam. Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, dignissimos.",
    img: "/img/reviewer-2.jpeg",
    profession: "Youtuber",
    rating: 5,
  },
];
